[package]
name = "brainrust"
version = "0.1.0"
edition = "2021"

[lints.rust]
unused = "allow"

[dependencies]
bytemuck = "1.18.0"
clap = { version = "4.5.17", features = ["derive"] }
enum-tag = "0.3.0"
nix = { version = "0.29.0", features = ["mman"] }
